pgcommitfest/urls.py
from django.urls import re_path
from django.contrib import admin

import pgcommitfest.commitfest.views as views
import pgcommitfest.commitfest.reports as reports
import pgcommitfest.commitfest.ajax as ajax
import pgcommitfest.commitfest.lookups as lookups
import pgcommitfest.auth
import pgcommitfest.userprofile.views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    re_path(r'^$', views.home),
    re_path(r'^activity(?P<rss>\.rss)?/', views.activity),
    re_path(r'^(\d+)/$', views.commitfest),
    re_path(r'^(open|inprogress|current)/(.*)$', views.redir),
    re_path(r'^(?P<cfid>\d+)/activity(?P<rss>\.rss)?/$', views.activity),
    re_path(r'^patch/(\d+)/$', views.patch_redirect),
    re_path(r'^(\d+)/(\d+)/$', views.patch),
    re_path(r'^(\d+)/(\d+)/edit/$', views.patchform),
    re_path(r'^(\d+)/new/$', views.newpatch),
    re_path(r'^(\d+)/(\d+)/status/(review|author|committer)/$', views.status),
    re_path(r'^(\d+)/(\d+)/close/(reject|withdrawn|feedback|committed|next)/$', views.close),
    re_path(r'^(\d+)/(\d+)/reviewer/(become|remove)/$', views.reviewer),
    re_path(r'^(\d+)/(\d+)/committer/(become|remove)/$', views.committer),
    re_path(r'^(\d+)/(\d+)/(un)?subscribe/$', views.subscribe),
    re_path(r'^(\d+)/(\d+)/(comment|review)/', views.comment),
    re_path(r'^(\d+)/send_email/$', views.send_email),
    re_path(r'^(\d+)/\d+/send_email/$', views.send_email),
    re_path(r'^(\d+)/reports/authorstats/$', reports.authorstats),
    re_path(r'^search/$', views.global_search),
    re_path(r'^ajax/(\w+)/$', ajax.main),
    re_path(r'^lookups/user/$', lookups.userlookup),
    re_path(r'^thread_notify/$', views.thread_notify),

    # Auth system integration
    re_path(r'^(?:account/)?login/?$', pgcommitfest.auth.login),
    re_path(r'^(?:account/)?logout/?$', pgcommitfest.auth.logout),
    re_path(r'^auth_receive/$', pgcommitfest.auth.auth_receive),
    re_path(r'^auth_api/$', pgcommitfest.auth.auth_api),

    # Account management
    re_path(r'^account/profile/$', pgcommitfest.userprofile.views.userprofile),

    # Examples:
    # re_path(r'^$', 'pgpgcommitfest.commitfest.views.home', name='home),
    # re_path(r'^pgcommitfest/', include('pgcommitfest.foo.urls)),

    # Uncomment the admin/doc line below to enable admin documentation:
    # re_path(r'^admin/doc/', include('django.contrib.admindocs.urls)),

    # Uncomment the next line to enable the admin:
    re_path(r'^admin/', admin.site.urls),
]

pgcommitfest/commitfest/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime

from .util import DiffableModel

from pgcommitfest.userprofile.models import UserProfile


# We have few enough of these, and it's really the only thing we
# need to extend from the user model, so just create a separate
# class.
class Committer(models.Model):
    user = models.OneToOneField(User, null=False, blank=False, primary_key=True, on_delete=models.CASCADE)
    active = models.BooleanField(null=False, blank=False, default=True)

    def __str__(self):
        return str(self.user)

    @property
    def fullname(self):
        return "%s %s (%s)" % (self.user.first_name, self.user.last_name, self.user.username)

    class Meta:
        ordering = ('user__last_name', 'user__first_name')


class CommitFest(models.Model):
    STATUS_FUTURE = 1
    STATUS_OPEN = 2
    STATUS_INPROGRESS = 3
    STATUS_CLOSED = 4
    _STATUS_CHOICES = (
        (STATUS_FUTURE, 'Future'),
        (STATUS_OPEN, 'Open'),
        (STATUS_INPROGRESS, 'In Progress'),
        (STATUS_CLOSED, 'Closed'),
    )
    name = models.CharField(max_length=100, blank=False, null=False, unique=True)
    status = models.IntegerField(null=False, blank=False, default=1, choices=_STATUS_CHOICES)
    startdate = models.DateField(blank=True, null=True)
    enddate = models.DateField(blank=True, null=True)

    @property
    def statusstring(self):
        return [v for k, v in self._STATUS_CHOICES if k == self.status][0]

    @property
    def periodstring(self):
        if self.startdate and self.enddate:
            return "{0} - {1}".format(self.startdate, self.enddate)
        return ""

    @property
    def title(self):
        return "Commitfest %s" % self.name

    @property
    def isopen(self):
        return self.status == self.STATUS_OPEN

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Commitfests'
        ordering = ('-startdate',)


class Topic(models.Model):
    topic = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.topic


class TargetVersion(models.Model):
    version = models.CharField(max_length=8, blank=False, null=False, unique=True)

    class Meta:
        ordering = ['-version', ]

    def __str__(self):
        return self.version


class Patch(models.Model, DiffableModel):
    name = models.CharField(max_length=500, blank=False, null=False, verbose_name='Description')
    topic = models.ForeignKey(Topic, blank=False, null=False, on_delete=models.CASCADE)

    # One patch can be in multiple commitfests, if it has history
    commitfests = models.ManyToManyField(CommitFest, through='PatchOnCommitFest')

    # If there is a wiki page discussing this patch
    wikilink = models.URLField(blank=True, null=False, default='')

    # If there is a git repo about this patch
    gitlink = models.URLField(blank=True, null=False, default='')

    # Version targeted by this patch
    targetversion = models.ForeignKey(TargetVersion, blank=True, null=True, verbose_name="Target version", on_delete=models.CASCADE)

    authors = models.ManyToManyField(User, related_name='patch_author', blank=True)
    reviewers = models.ManyToManyField(User, related_name='patch_reviewer', blank=True)

    committer = models.ForeignKey(Committer, blank=True, null=True, on_delete=models.CASCADE)

    # Users to be notified when something happens
    subscribers = models.ManyToManyField(User, related_name='patch_subscriber', blank=True)

    # Datestamps for tracking activity
    created = models.DateTimeField(blank=False, null=False, auto_now_add=True)
    modified = models.DateTimeField(blank=False, null=False)

    # Materialize the last time an email was sent on any of the threads
    # that's attached to this message.
    lastmail = models.DateTimeField(blank=True, null=True)

    map_manytomany_for_diff = {
        'authors': 'authors_string',
        'reviewers': 'reviewers_string',
    }

    # Some accessors
    @property
    def authors_string(self):
        return ", ".join(["%s %s (%s)" % (a.first_name, a.last_name, a.username) for a in self.authors.all()])

    @property
    def reviewers_string(self):
        return ", ".join(["%s %s (%s)" % (a.first_name, a.last_name, a.username) for a in self.reviewers.all()])

    @property
    def history(self):
        # Need to wrap this in a function to make sure it calls
        # select_related() and doesn't generate a bazillion queries
        return self.patchhistory_set.select_related('by').all()

    def set_modified(self, newmod=None):
        # Set the modified date to newmod, but only if that's newer than
        # what's currently set. If newmod is not specified, use the
        # current timestamp.
        if not newmod:
            newmod = datetime.now()
        if not self.modified or newmod > self.modified:
            self.modified = newmod

    def update_lastmail(self):
        # Update the lastmail field, based on the newest email in any of
        # the threads attached to it.
        threads = list(self.mailthread_set.all())
        if len(threads) == 0:
            self.lastmail = None
        else:
            self.lastmail = max(threads, key=lambda t: t.latestmessage).latestmessage

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'patches'


class PatchOnCommitFest(models.Model):
    # NOTE! This is also matched by the commitfest_patchstatus table,
    # but we hardcoded it in here simply for performance reasons since
    # the data should be entirely static. (Yes, that's something we
    # might re-evaluate in the future)
    STATUS_REVIEW = 1
    STATUS_AUTHOR = 2
    STATUS_COMMITTER = 3
    STATUS_COMMITTED = 4
    STATUS_NEXT = 5
    STATUS_REJECTED = 6
    STATUS_RETURNED = 7
    STATUS_WITHDRAWN = 8
    _STATUS_CHOICES = (
        (STATUS_REVIEW, 'Needs review'),
        (STATUS_AUTHOR, 'Waiting on Author'),
        (STATUS_COMMITTER, 'Ready for Committer'),
        (STATUS_COMMITTED, 'Committed'),
        (STATUS_NEXT, 'Moved to next CF'),
        (STATUS_REJECTED, 'Rejected'),
        (STATUS_RETURNED, 'Returned with feedback'),
        (STATUS_WITHDRAWN, 'Withdrawn'),
    )
    _STATUS_LABELS = (
        (STATUS_REVIEW, 'default'),
        (STATUS_AUTHOR, 'primary'),
        (STATUS_COMMITTER, 'info'),
        (STATUS_COMMITTED, 'success'),
        (STATUS_NEXT, 'warning'),
        (STATUS_REJECTED, 'danger'),
        (STATUS_RETURNED, 'danger'),
        (STATUS_WITHDRAWN, 'danger'),
    )
    OPEN_STATUSES = [STATUS_REVIEW, STATUS_AUTHOR, STATUS_COMMITTER]

    @classmethod
    def OPEN_STATUS_CHOICES(cls):
        return [x for x in cls._STATUS_CHOICES if x[0] in cls.OPEN_STATUSES]

    patch = models.ForeignKey(Patch, blank=False, null=False, on_delete=models.CASCADE)
    commitfest = models.ForeignKey(CommitFest, blank=False, null=False, on_delete=models.CASCADE)
    enterdate = models.DateTimeField(blank=False, null=False)
    leavedate = models.DateTimeField(blank=True, null=True)

    status = models.IntegerField(blank=False, null=False, default=STATUS_REVIEW, choices=_STATUS_CHOICES)

    @property
    def is_closed(self):
        return self.status not in self.OPEN_STATUSES

    @property
    def statusstring(self):
        return [v for k, v in self._STATUS_CHOICES if k == self.status][0]

    class Meta:
        unique_together = (('patch', 'commitfest',),)
        ordering = ('-commitfest__startdate', )


class PatchHistory(models.Model):
    patch = models.ForeignKey(Patch, blank=False, null=False, on_delete=models.CASCADE)
    date = models.DateTimeField(blank=False, null=False, auto_now_add=True, db_index=True)
    by = models.ForeignKey(User, blank=False, null=False, on_delete=models.CASCADE)
    what = models.CharField(max_length=500, null=False, blank=False)

    @property
    def by_string(self):
        return "%s %s (%s)" % (self.by.first_name, self.by.last_name, self.by.username)

    def __str__(self):
        return "%s - %s" % (self.patch.name, self.date)

    class Meta:
        ordering = ('-date', )

    def save_and_notify(self, prevcommitter=None,
                        prevreviewers=None, prevauthors=None):
        # Save this model, and then trigger notifications if there are any. There are
        # many different things that can trigger notifications, so try them all.
        self.save()

        recipients = []
        recipients.extend(self.patch.subscribers.all())

        # Current or previous committer wants all notifications
        try:
            if self.patch.committer and self.patch.committer.user.userprofile.notify_all_committer:
                recipients.append(self.patch.committer.user)
        except UserProfile.DoesNotExist:
            pass

        try:
            if prevcommitter and prevcommitter.user.userprofile.notify_all_committer:
                recipients.append(prevcommitter.user)
        except UserProfile.DoesNotExist:
            pass

        # Current or previous reviewers wants all notifications
        recipients.extend(self.patch.reviewers.filter(userprofile__notify_all_reviewer=True))
        if prevreviewers:
            # prevreviewers is a list
            recipients.extend(User.objects.filter(id__in=[p.id for p in prevreviewers], userprofile__notify_all_reviewer=True))

        # Current or previous authors wants all notifications
        recipients.extend(self.patch.authors.filter(userprofile__notify_all_author=True))

        for u in set(recipients):
            if u != self.by:  # Don't notify for changes we make ourselves
                PendingNotification(history=self, user=u).save()


class MailThread(models.Model):
    # This class tracks mail threads from the main postgresql.org
    # mailinglist archives. For each thread, we store *one* messageid.
    # Using this messageid we can always query the archives for more

pgcommitfest/commitfest/templates/activity.html
{%extends "base.html"%}
{%load commitfest %}
{%block contents%}

<table class="table table-striped table-bordered table-hover table-condensed">
 <thead>
  <tr>
   <th>Time</th>
   <th>User</th>
   <th>Patch</th>
   <th>Activity</th>
  </tr>
 </thead>
 <tbody>
{%for a in activity %}
  <tr>
    <td style="white-space: nowrap;">{{a.date}}</td>
    <td>{{a.by}}</td>
    <td><a href="/{%if commitfest%}{{commitfest.id}}{%else%}{{a.cfid}}{%endif%}/{{a.patchid}}/">{{a.name}}</a></td>
    <td>{{a.what}}</td>
  </tr>
{%endfor%}
 </tbody>
</table>

{%endblock%}

pgcommitfest/commitfest/templates/base.html
{%load commitfest%}
<!DOCTYPE html>
<html>
<head>
  <title>{{title}}</title>
  <link rel="stylesheet" href="/media/commitfest/css/jquery-ui.css" type="text/css">
  <link rel="stylesheet" href="/media/commitfest/css/bootstrap.css" />
  <link rel="stylesheet" href="/media/commitfest/css/bootstrap-theme.min.css" />
  <link rel="stylesheet" href="/media/commitfest/css/commitfest.css" />
  <link rel="shortcut icon" href="/media/commitfest/favicon.ico" />
{%block extrahead%}{%endblock%}
{%if rss_alternate%}  <link rel="alternate" type="application/rss+xml" title="{{rss_alternate_title}}" href="{{rss_alternate}}" />{%endif%}
</head>
<body>
<div class="container-fluid">
<ul class="breadcrumb">
 <li><a href="/">Home</a></li>
{%for c in breadcrumbs%}
 <li><a href="{{c.href}}">{{c.title}}</a></li>
{%endfor%}
 <li class="active">{{title}}</li>
 <li class="pull-right active">
{%if user.is_authenticated%}
 Logged in as {{user}} (<a href="/account/profile/">edit profile</a> | <a href="/account/logout/">log out</a>{%if user.is_staff%} | <a href="/admin/">administration</a>{%endif%})
{%else%}
 <a href="/account/login/?next={{request.path}}">Log in</a>
{%endif%}
 </li>
{%if header_activity%} <li class="pull-right active"><a href="{{header_activity_link}}">{{header_activity}}</a></li>{%endif%}
</ul>

<h1>{{title}}</h1>

{%if messages%}
 {%for m in messages%}
  <div class="alert {{m.tags|alertmap}}">{{m}}</div>
 {%endfor%}
{%endif%}

{%block contents%}
{%endblock%}
</div>
<script src="/media/commitfest/js/jquery.js"></script>
<script src="/media/commitfest/js/jquery-ui.js"></script>
<script src="/media/commitfest/js/bootstrap.js"></script>
<script src="/media/commitfest/js/commitfest.js"></script>
{%block morescript%}{%endblock%}
</html>

pgcommitfest/commitfest/templates/base_form.html
{%extends "base.html"%}
{%load commitfest%}

{%block contents%}
<form class="form-horizontal {{extraformclass}}" method="POST" action=".">{%csrf_token%}
{%if form.errors%}
 <div class="alert">Please correct the errors below, and re-submit the form.</div>
{%endif%}
{%if form.non_field_errors%}
 <div class="alert alert-danger">{{form.non_field_errors}}</div>
{%endif%}
{%if note%}
<div class="alert alert-info">{{note|safe}}</div>
{%endif%}
 {%for field in form%}
 {%if not field.is_hidden%}
 <div class="form-group">
   {{field|label_class:"control-label col-lg-1"}}
   <div class="col-lg-11 controls">
  {%if field.errors %}
   {%for e in field.errors%}
 <div class="alert alert-danger">{{e}}</div>
   {%endfor%}
  {%endif%}
{%if not field.name in form.selectize_multiple_fields%}{{field|field_class:"form-control"}}{%else%}{{field}}{%endif%}
{%if field.help_text%}<br/>{{field.help_text|safe}}{%endif%}</div>
 </div>
 {%else%}
{{field}}
 {%endif%}
{%endfor%}
 <div class="form-group">
  <div class="col-lg-12">
   <div class="control"><input type="submit" class="btn btn-default" value="{{savebutton|default:"Save"}}"></div>
  </div>
 </div>
</form>

{%if threadbrowse %}
{%include "thread_attach.inc" %}
{%endif%}

{%if user.is_staff%}
<div class="modal fade" id="searchUserModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3>Search user</h3>
      </div>
      <div class="modal-body">
	<form class="form-inline" style="margin-bottom: 5px;">
	  <div class="input-append">
	    <input id="searchUserSearchField" type="text" class="span2 search-query" autocomplete="off">
	    <button id="searchUserSearchButton" onclick="return findUsers()" class="btn btn-default">Search</button>
	  </div>
	</form>
	<div>Search for users above and then pick one in the list below:</div>
	<div id="searchUserListWrap">
	  <select id="searchUserList" size="6" style="width:100%;" onchange="searchUserListChanged()"></select>
	</div>
      </div>
      <div class="modal-footer">
	<a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
	<a href="#" id="doSelectUserButton" class="btn btn-default btn-primary disabled">Add user to system</a>
      </div>
    </div>
  </div>
</div>
{%endif%}
{%endblock%}

{%block extrahead%}
<link rel="stylesheet" href="/media/commitfest/css/selectize.css" />
<link rel="stylesheet" href="/media/commitfest/css/selectize.default.css" />
{%endblock%}
{%block morescript%}
<script src="/media/commitfest/js/selectize.min.js"></script>
<script>
/* Set up selectize fields */
{% for f, url in selectize_multiple_fields %}
   $('#id_{{f}}').selectize({
      plugins: ['remove_button'],
      valueField: 'id',
      labelField: 'value',
      searchField: 'value',
      load: function(query, callback) {
         if (!query.length) return callback();
         $.ajax({
            'url': '{{url}}',
            'type': 'GET',
            'dataType': 'json',
            'data': {
               'query': query,
            },
            'error': function() { callback();},
            'success': function(res) { callback(res.values);},
         });
      }
   });
{%endfor%}
{%if user.is_staff%}
   $('.selectize-control').after(
      $('<a href="#" class="btn btn-default btn-sm">Import user not listed</a>').click(function () {
          search_and_store_user();
      })
   );

$('#searchUserModal').on('shown.bs.modal', function() {
	  $('#searchUserSearchField').focus();
});
{%endif%}

/* Build our button callbacks */
$(document).ready(function() {
   $('button.attachThreadButton').each(function (i,o) {
      var b = $(o);
      b.click(function() {
	 $('#attachThreadAttachOnly').val('1');
         browseThreads(function(msgid) {
            b.prev().val(msgid);
            return true;
         });
         return false;
      });
   });
});
</script>
{%endblock%}

pgcommitfest/commitfest/templates/commitfest.html
{%extends "base.html"%}
{%load commitfest %}
{%block contents%}

<button type="button" class="btn btn-default{%if has_filter%} active{%endif%}" id="filterButton" onClick="togglePatchFilterButton('filterButton', 'collapseFilters')">Search/filter</button>
<div class="btn-group">
  <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">Shortcuts <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="?reviewer=-2">Patches with no reviewers</a></li>
    <li><a href="?author=-3">Patches where you are author</a></li>
    <li><a href="?reviewer=-3">Patches where you are reviewer</a></li>
  </ul>
</div>
{%if cf.isopen or user.is_staff %}
<a class="btn btn-default" href="new/">New patch</a>
{%endif%}
<div id="collapseFilters" class="collapse {%if has_filter%}in{%endif%}">
    <form id="filterform" method="GET" action="." style="margin-bottom: 0px">
      <table class="table table-condensed" style="margin-bottom: 0px">
	<thead>
	  <tr>
{%for f in form%}
         {%if not f.is_hidden%}
            <td>{{f.label}}</td>
	 {%else%}
	    <td></td>
	 {%endif%}
{%endfor%}
	    {%comment%} Add one extra for buttons {%endcomment%}
	    <td></td>
	  </tr>
	</thead>
	<tbody>
	  <tr>
{%for f in form%}
            <td>{{f|field_class:"form-control"}}</td>
{%endfor%}
	    <td>
	      <input type="submit" class="btn btn-default" value="Filter">
	      <a class="btn btn-default" href=".">Clear</a>
	    </td>
	  </tr>
	</tbody>
      </table>
    </form>
</div>

<p>
<br/>
<b>Status summary: </b>{%for id,title,num in statussummary%}<a href="?status={{id}}">{{title}}</a>: {{num}}. {%endfor%}
</p>

{%for p in patches %}
{%ifchanged p.is_open%}
{%if not forloop.first%}
 </tbody>
</table>
{%endif%}
<h3>{{p.is_open|yesno:"Active patches,Closed patches"}}</h3>
<table class="table table-striped table-bordered table-hover table-condensed">
 <thead>
  <tr>
   <th>{%if p.is_open%}<a href="#" style="color:#333333;" onclick="return sortpatches(0);">Patch</a>{%if sortkey == 0%}<div style="float:right;"><i class="glyphicon glyphicon-arrow-down"></i></div>{%endif%}{%endif%}</th>
   <th>Status</th>
   <th>Ver</th>
   <th>Author</th>
   <th>Reviewers</th>
   <th>Committer</th>
   <th>{%if p.is_open%}<a href="#" style="color:#333333;" onclick="return sortpatches(3);">Num cfs</a>{%if sortkey == 3%}<div style="float:right;"><i class="glyphicon glyphicon-arrow-down"></i></div>{%endif%}{%else%}Num cfs{%endif%}</th>
   <th>{%if p.is_open%}<a href="#" style="color:#333333;" onclick="return sortpatches(1);">Latest activity</a>{%if sortkey == 1%}<div style="float:right;"><i class="glyphicon glyphicon-arrow-down"></i></div>{%endif%}{%else%}Latest activity{%endif%}</th>
   <th>{%if p.is_open%}<a href="#" style="color:#333333;" onclick="return sortpatches(2);">Latest mail</a>{%if sortkey == 2%}<div style="float:right;"><i class="glyphicon glyphicon-arrow-down"></i></div>{%endif%}{%else%}Latest mail{%endif%}</th>
{%if user.is_staff%}
   <th>Select</th>
{%endif%}
  </tr>
 </thead>
 <tbody>
{%endifchanged%}

{%if grouping%}
{%ifchanged p.topic%}
  <tr><th colspan="{%if user.is_staff%}10{%else%}9{%endif%}">{{p.topic}}</th></tr>
{%endifchanged%} 
{%endif%}
  <tr>
   <td><a href="{{p.id}}/">{{p.name}}</a></td>
   <td><span class="label label-{{p.status|patchstatuslabel}}">{{p.status|patchstatusstring}}</span></td>
   <td>{%if p.targetversion%}<span class="label label-default">{{p.targetversion}}</span>{%endif%}</td>
   <td>{{p.author_names|default:''}}</td>
   <td>{{p.reviewer_names|default:''}}</td>
   <td>{{p.committer|default:''}}</td>
   <td>{{p.num_cfs}}</td>
   <td style="white-space: nowrap;">{{p.modified|date:"Y-m-d"}}<br/>{{p.modified|date:"H:i"}}</td>
   <td style="white-space: nowrap;">{{p.lastmail|date:"Y-m-d"}}<br/>{{p.lastmail|date:"H:i"}}</td>
{%if user.is_staff%}
   <td style="white-space: nowrap;"><input type="checkbox" class="sender_checkbox" id="send_authors_{{p.id}}">Author<br/><input type="checkbox" class="sender_checkbox" id="send_reviewers_{{p.id}}">Reviewer</td>
{%endif%}
  </tr>
{%if forloop.last%}
 </tbody>
</table>
{%endif%}
{%endfor%}

<div>
{%if cf.isopen or user.is_staff %}
<a class="btn btn-default" href="new/">New patch</a>
{%endif%}
{%if user.is_staff%}
 <div class="btn-group dropup">
  <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" href="#">Send private mail <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><a href="javascript:send_selected()">Selected</a></li>
    <li><a href="send_email/?reviewers={{openpatchids|join:","}}">All reviewers (open patches)</a></li>
    <li><a href="send_email/?authors={{openpatchids|join:","}}">All authors (open patches)</a></li>
    <li><a href="send_email/?authors={{openpatchids|join:","}}&reviewers={{openpatchids|join:","}}">All authors and reviewers (open patches)</a></li>
  </ul>
 </div>

 <div class="btn-group dropup">
   <button type="button" class="btn btn-default dropdown-toggle " data-toggle="dropdown" href="#">Reports <span class="caret"></span></button>
   <ul class="dropdown-menu">
     <li><a href="reports/authorstats/">Author stats</a></li>
   </ul>
 </div>
{%endif%}
</div>
{%endblock%}

{%block morescript%}
<script>
{%if user.is_staff%}
   function send_selected() {
      var authors = [];
      var reviewers = [];
      $('input.sender_checkbox').each(function(index, el) {
         if (el.checked) {
            if (el.id.indexOf('send_authors_') == 0) {
               authors.push(el.id.substring(13));
            } else {
               reviewers.push(el.id.substring(15));
            }
         }
      });
      if (authors.length==0 && reviewers.length==0) {
         alert('Nothing to send.');
         return;
      }
      document.location.href = 'send_email/?authors=' + authors.join(',') + '&reviewers=' + reviewers.join(',');
   }
{%endif%}
</script>
{%endblock%}

pgcommitfest/commitfest/templates/patchsearch.html
{%extends "base.html"%}
{%load commitfest %}
{%block contents%}

<form method="GET" action="/search/" class="form-inline" style="margin-bottom: 10px">
  <div class="form-group">
    <input type="text" class="form-control" id="searchterm" name="searchterm" placeholder="Global search">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>

<table class="table table-striped table-bordered table-hover table-condensed">
 <thead>
  <tr>
   <th>Patch</th>
   <th>Status</th>
   <th>Author</th>
  </tr>
 </thead>
 <tbody>
{%for p in patches %}
 {%with p.patchoncommitfest_set.all as cfs %}
  <tr>
   <td>{%with cfs|first as firstcf%}<a href="/{{firstcf.commitfest_id}}/{{p.id}}/">{{p}}</a>{%endwith%}</td>
   <td>{%for c in cfs %}
	<div style="margin-bottom: 3px;">{{c.commitfest}}: <span class="label label-default">{{c.statusstring}}</span></div>
	{%endfor%}</td>
   <td>{{p.authors_string|default:''}}</td>
  </tr>
 {%endwith%}
{%endfor%}
 </tbody>
</table>

{%endblock%}